# Generated by Django 5.2.6 on 2025-09-07 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('link', models.URLField(help_text='Absolute or relative URL to launch the game')),
                ('slug', models.SlugField(help_text='Stable identifier for the game', max_length=120, unique=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordering on the homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
