# Generated by Django 5.2.6 on 2025-09-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='asset',
            field=models.FileField(blank=True, help_text='Optional downloadable file (e.g., zip, instructions)', null=True, upload_to='games/assets/'),
        ),
        migrations.AddField(
            model_name='game',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Hide/show this game on the homepage'),
        ),
        migrations.AddField(
            model_name='game',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Optional thumbnail image shown on the homepage', null=True, upload_to='games/thumbnails/'),
        ),
    ]
